server:
  port: 8012
spring:
  hateoas:
    use-hal-as-default-json-media-type: true
  application:
    name: microservice-consumer-user

eureka:
  client:
    serviceUrl:
      defaultZone: http://enreka1:8000/eureka/
  instance:
    preferIpAddress: true